# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImYMZFvXB2VNbwdeQns9nw3n_eOsTK5E
"""

import numpy as np
import matplotlib.pyplot as plt

# X qiymatlarini aniqlaymiz
x = np.linspace(0, 10, 100)  # 0 dan 10 gacha 100 ta nuqta
y = np.sin(x)  # Sinus funksiyasini hisoblash

# Grafikni chizamiz
plt.plot(x, y, label="Sinus(x)", color="blue")
plt.title("Sinus Funksiyasining Grafiki")  # Grafik sarlavhasi
plt.xlabel("X qiymatlari")  # X o'q nomi
plt.ylabel("Y qiymatlari")  # Y o'q nomi
plt.legend()  # Grafikning yorlig'i
plt.grid(True)  # Gridlar qo'shish
plt.show()  # Grafikni chiqarish

import matplotlib.pyplot as plt
import numpy as np

# Tasodifiy nuqtalarni yaratish
x = np.random.uniform(0, 10, 50)  # X qiymatlari (0 dan 10 gacha bo'lgan 50 ta nuqta)
y = np.random.uniform(0, 10, 50)  # Y qiymatlari (0 dan 10 gacha bo'lgan 50 ta nuqta)

# Scatter diagramma yaratish
plt.figure(figsize=(8, 6))  # Grafik o'lchamini o'rnatish
plt.scatter(x, y, color='blue', s=100, alpha=0.7, label='Nuqtalar')  # Nuqtalarni chizish
plt.title("Tasodifiy Nuqtalar Scatter Grafiki")  # Grafik nomi
plt.xlabel("X qiymatlari")  # X o'q nomi
plt.ylabel("Y qiymatlari")  # Y o'q nomi
plt.legend()  # Legend qo'shish
plt.grid(True)  # Panjara qo'shish
plt.show()  # Grafikni ko'rsatish